/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as governanceStandard from "./governance_standard";
export type { governanceStandard };
export type { GovernanceToken } from "./GovernanceToken";
export type { Own } from "./Own";
